services:
  postgres:
    image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/postgres:17
    container_name: postgres-server
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - postgres-network

  adminer:
    image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/adminer:latest
    container_name: postgres-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    networks:
      - postgres-network

volumes:
  postgres-data:
    driver: local

networks:
  postgres-network:
    driver: bridge
