// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
  category?: string | null
  task_type?: string | null
  target_count?: number
  coins_reward?: number
}

export type ItemPublic = {
  title: string
  description?: string | null
  category?: string | null
  task_type?: string | null
  target_count?: number
  coins_reward?: number
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
  category?: string | null
  task_type?: string | null
  target_count?: number
  coins_reward?: number
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  coins?: number
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type TaskCompletionPublic = {
  completed_at: string
  id: string
  item_id: string
  user_id: string
}

export type TodayTaskPublic = {
  id: string
  title: string
  description?: string | null
  category?: string | null
  task_type?: string | null
  target_count: number
  completed_count: number
  completed_today: boolean
}

export type TodayTasksPublic = {
  data: Array<TodayTaskPublic>
  count: number
}

export type CoinLogPublic = {
  name: string
  completed_at: string
  amount: number
}

export type CoinLogsPublic = {
  data: Array<CoinLogPublic>
  count: number
}

export type TaskCompletionsGetTodayCoinLogsResponse = CoinLogsPublic

export type TaskCompletionsGetTodayTasksResponse = TodayTasksPublic

export type TaskCompletionsCompleteTaskData = {
  itemId: string
}

export type TaskCompletionsCompleteTaskResponse = TaskCompletionPublic

export type TaskCompletionsGetHistoryData = {
  itemId: string
}

export type TaskCompletionsGetHistoryResponse = Array<TaskCompletionPublic>

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean

// Prize types
export type PrizeCreate = {
  name: string
  description?: string | null
  image_url?: string | null
  product_url?: string | null
  price?: number | null
  coins_cost?: number
  stock?: number
}

export type PrizePublic = {
  name: string
  description?: string | null
  image_url?: string | null
  product_url?: string | null
  price?: number | null
  coins_cost: number
  stock: number
  id: string
  created_at: string
}

export type PrizesPublic = {
  data: Array<PrizePublic>
  count: number
}

export type PrizeUpdate = {
  name?: string | null
  description?: string | null
  image_url?: string | null
  product_url?: string | null
  price?: number | null
  coins_cost?: number | null
  stock?: number | null
}

export type TaobaoProductInfo = {
  name: string
  price?: number | null
  image_url?: string | null
}

export type PrizesReadPrizesData = {
  limit?: number
  skip?: number
}

export type PrizesReadPrizesResponse = PrizesPublic

export type PrizesReadPrizeData = {
  id: string
}

export type PrizesReadPrizeResponse = PrizePublic

export type PrizesCreatePrizeData = {
  requestBody: PrizeCreate
}

export type PrizesCreatePrizeResponse = PrizePublic

export type PrizesUpdatePrizeData = {
  id: string
  requestBody: PrizeUpdate
}

export type PrizesUpdatePrizeResponse = PrizePublic

export type PrizesDeletePrizeData = {
  id: string
}

export type PrizesDeletePrizeResponse = Message

export type PrizesParseTaobaoUrlData = {
  url: string
}

export type PrizesParseTaobaoUrlResponse = TaobaoProductInfo

// ─── Growth Record types ─────────────────────────────────────────

export type DailyCompletionPoint = {
  date: string
  count: number
}

export type HeatmapData = {
  days: Array<DailyCompletionPoint>
  current_streak: number
  longest_streak: number
  total_completions: number
}

export type CategoryStats = {
  category: string
  count: number
  coins_earned: number
}

export type PeriodComparison = {
  current_count: number
  previous_count: number
  current_coins: number
  previous_coins: number
  change_rate: number
}

export type ProgressReport = {
  period: string
  comparison: PeriodComparison
  category_stats: Array<CategoryStats>
  daily_trend: Array<DailyCompletionPoint>
  summary: string
}

export type PrizeRedemptionPublic = {
  coins_spent: number
  redeemed_at: string
  id: string
  user_id: string
  prize_id: string
  prize_name: string
}

export type PrizeRedemptionsPublic = {
  data: Array<PrizeRedemptionPublic>
  count: number
}

export type RewardSummary = {
  total_coins_earned: number
  total_coins_spent: number
  current_balance: number
  category_earnings: Array<CategoryStats>
  recent_redemptions: Array<PrizeRedemptionPublic>
}

export type GrowthGetHeatmapData = {
  days?: number
  userId?: string
}

export type GrowthGetHeatmapResponse = HeatmapData

export type GrowthGetProgressData = {
  period?: string
  userId?: string
}

export type GrowthGetProgressResponse = ProgressReport

export type GrowthGetRewardsData = {
  userId?: string
}

export type GrowthGetRewardsResponse = RewardSummary

export type GrowthRedeemPrizeData = {
  prizeId: string
}

export type GrowthRedeemPrizeResponse = PrizeRedemptionPublic

export type GrowthGetRedemptionsData = {
  skip?: number
  limit?: number
  userId?: string
}

export type GrowthGetRedemptionsResponse = PrizeRedemptionsPublic
