"""add_prize_redemption_enhancements_and_coin_logs

Revision ID: 07cd01068927
Revises: k8l9m0n1o2p3
Create Date: 2026-04-08 19:09:33.624626

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '07cd01068927'
down_revision = 'k8l9m0n1o2p3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # prizetype/redemptionstatus/userrole are only used in add_column/alter_column,
    # so SQLAlchemy won't auto-create them - we must do it manually.
    # transactiontype is in create_table(coinlog) so it gets auto-created.
    op.execute("CREATE TYPE prizetype AS ENUM ('physical', 'virtual')")
    op.execute("CREATE TYPE redemptionstatus AS ENUM ('pending', 'processing', 'completed', 'cancelled', 'refunded')")
    op.execute("CREATE TYPE userrole AS ENUM ('admin', 'user')")

    op.create_table('coinlog',
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('task_completion', 'prize_redemption', 'admin_adjustment', 'refund', 'referral_bonus', name='transactiontype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('related_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shippingaddress',
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('recipient_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('detail_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('prize', sa.Column('prize_type', sa.Enum('physical', 'virtual', name='prizetype'), nullable=False, server_default='physical'))
    op.add_column('prize', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('prize', sa.Column('total_redeemed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('prize', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('prizeredemption', sa.Column('prize_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='physical'))
    op.add_column('prizeredemption', sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'cancelled', 'refunded', name='redemptionstatus'), nullable=False, server_default='completed'))
    op.add_column('prizeredemption', sa.Column('shipping_address_id', sa.Uuid(), nullable=True))
    op.add_column('prizeredemption', sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('prizeredemption', sa.Column('recipient_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('prizeredemption', sa.Column('recipient_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('prizeredemption', sa.Column('tracking_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('prizeredemption', sa.Column('shipping_company', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('prizeredemption', sa.Column('shipped_at', sa.DateTime(), nullable=True))
    op.add_column('prizeredemption', sa.Column('admin_note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('prizeredemption', sa.Column('user_note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('prizeredemption', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('prizeredemption', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.drop_constraint('prizeredemption_prize_id_fkey', 'prizeredemption', type_='foreignkey')
    op.create_foreign_key(None, 'prizeredemption', 'prize', ['prize_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'prizeredemption', 'shippingaddress', ['shipping_address_id'], ['id'])
    op.drop_index('ix_taskcompletion_completed_at', table_name='taskcompletion')
    op.drop_index('ix_taskcompletion_item_id', table_name='taskcompletion')
    op.drop_index('ix_taskcompletion_user_id', table_name='taskcompletion')
    # Change user.role from VARCHAR to userrole enum
    # Step 1: Drop the default
    op.alter_column('user', 'role', server_default=None)
    # Step 2: Change type with USING clause
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('admin', 'user', name='userrole'),
               existing_nullable=False,
               postgresql_using='role::userrole')
    # Step 3: Re-add the default
    op.alter_column('user', 'role', server_default=sa.text("'user'::userrole"))
    op.drop_constraint('uq_user_referral_code', 'user', type_='unique')
    op.drop_constraint('fk_user_referred_by_id', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user', ['referred_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('fk_user_referred_by_id', 'user', 'user', ['referred_by_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_user_referral_code', 'user', ['referral_code'])
    op.alter_column('user', 'role',
               existing_type=sa.Enum('admin', 'user', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.create_index('ix_taskcompletion_user_id', 'taskcompletion', ['user_id'], unique=False)
    op.create_index('ix_taskcompletion_item_id', 'taskcompletion', ['item_id'], unique=False)
    op.create_index('ix_taskcompletion_completed_at', 'taskcompletion', ['completed_at'], unique=False)
    op.drop_constraint(None, 'prizeredemption', type_='foreignkey')
    op.drop_constraint(None, 'prizeredemption', type_='foreignkey')
    op.create_foreign_key('prizeredemption_prize_id_fkey', 'prizeredemption', 'prize', ['prize_id'], ['id'], ondelete='CASCADE')
    op.drop_column('prizeredemption', 'cancelled_at')
    op.drop_column('prizeredemption', 'completed_at')
    op.drop_column('prizeredemption', 'user_note')
    op.drop_column('prizeredemption', 'admin_note')
    op.drop_column('prizeredemption', 'shipped_at')
    op.drop_column('prizeredemption', 'shipping_company')
    op.drop_column('prizeredemption', 'tracking_number')
    op.drop_column('prizeredemption', 'recipient_address')
    op.drop_column('prizeredemption', 'recipient_phone')
    op.drop_column('prizeredemption', 'recipient_name')
    op.drop_column('prizeredemption', 'shipping_address_id')
    op.drop_column('prizeredemption', 'status')
    op.drop_column('prizeredemption', 'prize_type')
    op.drop_column('prize', 'updated_at')
    op.drop_column('prize', 'total_redeemed')
    op.drop_column('prize', 'is_active')
    op.drop_column('prize', 'prize_type')
    op.drop_table('shippingaddress')
    op.drop_table('coinlog')
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS userrole")
    op.execute("DROP TYPE IF EXISTS transactiontype")
    op.execute("DROP TYPE IF EXISTS redemptionstatus")
    op.execute("DROP TYPE IF EXISTS prizetype")
    # ### end Alembic commands ###
