/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as RedemptionsIndexRouteImport } from './routes/redemptions/index'
import { Route as CoinLogsIndexRouteImport } from './routes/coin-logs/index'
import { Route as AddressesIndexRouteImport } from './routes/addresses/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as LandingParentRouteImport } from './routes/landing/parent'
import { Route as CoinsLogsRouteImport } from './routes/coins/logs'
import { Route as LayoutTasksRouteImport } from './routes/_layout/tasks'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReferralRouteImport } from './routes/_layout/referral'
import { Route as LayoutPrizesRouteImport } from './routes/_layout/prizes'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutGrowthRouteImport } from './routes/_layout/growth'
import { Route as LayoutCodingRouteImport } from './routes/_layout/coding'
import { Route as LayoutChildrenRouteImport } from './routes/_layout/children'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAchievementsRouteImport } from './routes/_layout/achievements'
import { Route as LayoutExamsIndexRouteImport } from './routes/_layout/exams/index'
import { Route as LayoutCodingIndexRouteImport } from './routes/_layout/coding/index'
import { Route as LayoutParentSdiRouteImport } from './routes/_layout/parent/sdi'
import { Route as LayoutParentMonitorRouteImport } from './routes/_layout/parent/monitor'
import { Route as LayoutParentExamsRouteImport } from './routes/_layout/parent/exams'
import { Route as LayoutCodingEditorRouteImport } from './routes/_layout/coding/editor'
import { Route as LayoutExamsReportSessionIdRouteImport } from './routes/_layout/exams/report/$sessionId'
import { Route as LayoutExamsPlaySessionIdRouteImport } from './routes/_layout/exams/play/$sessionId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const RedemptionsIndexRoute = RedemptionsIndexRouteImport.update({
  id: '/redemptions/',
  path: '/redemptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinLogsIndexRoute = CoinLogsIndexRouteImport.update({
  id: '/coin-logs/',
  path: '/coin-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesIndexRoute = AddressesIndexRouteImport.update({
  id: '/addresses/',
  path: '/addresses/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingParentRoute = LandingParentRouteImport.update({
  id: '/landing/parent',
  path: '/landing/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsLogsRoute = CoinsLogsRouteImport.update({
  id: '/coins/logs',
  path: '/coins/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTasksRoute = LayoutTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReferralRoute = LayoutReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrizesRoute = LayoutPrizesRouteImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGrowthRoute = LayoutGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCodingRoute = LayoutCodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChildrenRoute = LayoutChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAchievementsRoute = LayoutAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamsIndexRoute = LayoutExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCodingIndexRoute = LayoutCodingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCodingRoute,
} as any)
const LayoutParentSdiRoute = LayoutParentSdiRouteImport.update({
  id: '/parent/sdi',
  path: '/parent/sdi',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutParentMonitorRoute = LayoutParentMonitorRouteImport.update({
  id: '/parent/monitor',
  path: '/parent/monitor',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutParentExamsRoute = LayoutParentExamsRouteImport.update({
  id: '/parent/exams',
  path: '/parent/exams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCodingEditorRoute = LayoutCodingEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => LayoutCodingRoute,
} as any)
const LayoutExamsReportSessionIdRoute =
  LayoutExamsReportSessionIdRouteImport.update({
    id: '/exams/report/$sessionId',
    path: '/exams/report/$sessionId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutExamsPlaySessionIdRoute =
  LayoutExamsPlaySessionIdRouteImport.update({
    id: '/exams/play/$sessionId',
    path: '/exams/play/$sessionId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof LayoutAchievementsRoute
  '/admin': typeof LayoutAdminRoute
  '/children': typeof LayoutChildrenRoute
  '/coding': typeof LayoutCodingRouteWithChildren
  '/growth': typeof LayoutGrowthRoute
  '/items': typeof LayoutItemsRoute
  '/prizes': typeof LayoutPrizesRoute
  '/referral': typeof LayoutReferralRoute
  '/settings': typeof LayoutSettingsRoute
  '/tasks': typeof LayoutTasksRoute
  '/coins/logs': typeof CoinsLogsRoute
  '/landing/parent': typeof LandingParentRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/addresses/': typeof AddressesIndexRoute
  '/coin-logs/': typeof CoinLogsIndexRoute
  '/redemptions/': typeof RedemptionsIndexRoute
  '/coding/editor': typeof LayoutCodingEditorRoute
  '/parent/exams': typeof LayoutParentExamsRoute
  '/parent/monitor': typeof LayoutParentMonitorRoute
  '/parent/sdi': typeof LayoutParentSdiRoute
  '/coding/': typeof LayoutCodingIndexRoute
  '/exams/': typeof LayoutExamsIndexRoute
  '/exams/play/$sessionId': typeof LayoutExamsPlaySessionIdRoute
  '/exams/report/$sessionId': typeof LayoutExamsReportSessionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof LayoutAchievementsRoute
  '/admin': typeof LayoutAdminRoute
  '/children': typeof LayoutChildrenRoute
  '/growth': typeof LayoutGrowthRoute
  '/items': typeof LayoutItemsRoute
  '/prizes': typeof LayoutPrizesRoute
  '/referral': typeof LayoutReferralRoute
  '/settings': typeof LayoutSettingsRoute
  '/tasks': typeof LayoutTasksRoute
  '/coins/logs': typeof CoinsLogsRoute
  '/landing/parent': typeof LandingParentRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof LayoutIndexRoute
  '/addresses': typeof AddressesIndexRoute
  '/coin-logs': typeof CoinLogsIndexRoute
  '/redemptions': typeof RedemptionsIndexRoute
  '/coding/editor': typeof LayoutCodingEditorRoute
  '/parent/exams': typeof LayoutParentExamsRoute
  '/parent/monitor': typeof LayoutParentMonitorRoute
  '/parent/sdi': typeof LayoutParentSdiRoute
  '/coding': typeof LayoutCodingIndexRoute
  '/exams': typeof LayoutExamsIndexRoute
  '/exams/play/$sessionId': typeof LayoutExamsPlaySessionIdRoute
  '/exams/report/$sessionId': typeof LayoutExamsReportSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/achievements': typeof LayoutAchievementsRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/children': typeof LayoutChildrenRoute
  '/_layout/coding': typeof LayoutCodingRouteWithChildren
  '/_layout/growth': typeof LayoutGrowthRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/prizes': typeof LayoutPrizesRoute
  '/_layout/referral': typeof LayoutReferralRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tasks': typeof LayoutTasksRoute
  '/coins/logs': typeof CoinsLogsRoute
  '/landing/parent': typeof LandingParentRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_layout/': typeof LayoutIndexRoute
  '/addresses/': typeof AddressesIndexRoute
  '/coin-logs/': typeof CoinLogsIndexRoute
  '/redemptions/': typeof RedemptionsIndexRoute
  '/_layout/coding/editor': typeof LayoutCodingEditorRoute
  '/_layout/parent/exams': typeof LayoutParentExamsRoute
  '/_layout/parent/monitor': typeof LayoutParentMonitorRoute
  '/_layout/parent/sdi': typeof LayoutParentSdiRoute
  '/_layout/coding/': typeof LayoutCodingIndexRoute
  '/_layout/exams/': typeof LayoutExamsIndexRoute
  '/_layout/exams/play/$sessionId': typeof LayoutExamsPlaySessionIdRoute
  '/_layout/exams/report/$sessionId': typeof LayoutExamsReportSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/achievements'
    | '/admin'
    | '/children'
    | '/coding'
    | '/growth'
    | '/items'
    | '/prizes'
    | '/referral'
    | '/settings'
    | '/tasks'
    | '/coins/logs'
    | '/landing/parent'
    | '/oauth/callback'
    | '/addresses/'
    | '/coin-logs/'
    | '/redemptions/'
    | '/coding/editor'
    | '/parent/exams'
    | '/parent/monitor'
    | '/parent/sdi'
    | '/coding/'
    | '/exams/'
    | '/exams/play/$sessionId'
    | '/exams/report/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/achievements'
    | '/admin'
    | '/children'
    | '/growth'
    | '/items'
    | '/prizes'
    | '/referral'
    | '/settings'
    | '/tasks'
    | '/coins/logs'
    | '/landing/parent'
    | '/oauth/callback'
    | '/'
    | '/addresses'
    | '/coin-logs'
    | '/redemptions'
    | '/coding/editor'
    | '/parent/exams'
    | '/parent/monitor'
    | '/parent/sdi'
    | '/coding'
    | '/exams'
    | '/exams/play/$sessionId'
    | '/exams/report/$sessionId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_layout/achievements'
    | '/_layout/admin'
    | '/_layout/children'
    | '/_layout/coding'
    | '/_layout/growth'
    | '/_layout/items'
    | '/_layout/prizes'
    | '/_layout/referral'
    | '/_layout/settings'
    | '/_layout/tasks'
    | '/coins/logs'
    | '/landing/parent'
    | '/oauth/callback'
    | '/_layout/'
    | '/addresses/'
    | '/coin-logs/'
    | '/redemptions/'
    | '/_layout/coding/editor'
    | '/_layout/parent/exams'
    | '/_layout/parent/monitor'
    | '/_layout/parent/sdi'
    | '/_layout/coding/'
    | '/_layout/exams/'
    | '/_layout/exams/play/$sessionId'
    | '/_layout/exams/report/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CoinsLogsRoute: typeof CoinsLogsRoute
  LandingParentRoute: typeof LandingParentRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  AddressesIndexRoute: typeof AddressesIndexRoute
  CoinLogsIndexRoute: typeof CoinLogsIndexRoute
  RedemptionsIndexRoute: typeof RedemptionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redemptions/': {
      id: '/redemptions/'
      path: '/redemptions'
      fullPath: '/redemptions/'
      preLoaderRoute: typeof RedemptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin-logs/': {
      id: '/coin-logs/'
      path: '/coin-logs'
      fullPath: '/coin-logs/'
      preLoaderRoute: typeof CoinLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses/': {
      id: '/addresses/'
      path: '/addresses'
      fullPath: '/addresses/'
      preLoaderRoute: typeof AddressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/parent': {
      id: '/landing/parent'
      path: '/landing/parent'
      fullPath: '/landing/parent'
      preLoaderRoute: typeof LandingParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins/logs': {
      id: '/coins/logs'
      path: '/coins/logs'
      fullPath: '/coins/logs'
      preLoaderRoute: typeof CoinsLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/tasks': {
      id: '/_layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/referral': {
      id: '/_layout/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof LayoutReferralRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/prizes': {
      id: '/_layout/prizes'
      path: '/prizes'
      fullPath: '/prizes'
      preLoaderRoute: typeof LayoutPrizesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/growth': {
      id: '/_layout/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof LayoutGrowthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coding': {
      id: '/_layout/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof LayoutCodingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/children': {
      id: '/_layout/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof LayoutChildrenRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/achievements': {
      id: '/_layout/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof LayoutAchievementsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exams/': {
      id: '/_layout/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof LayoutExamsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coding/': {
      id: '/_layout/coding/'
      path: '/'
      fullPath: '/coding/'
      preLoaderRoute: typeof LayoutCodingIndexRouteImport
      parentRoute: typeof LayoutCodingRoute
    }
    '/_layout/parent/sdi': {
      id: '/_layout/parent/sdi'
      path: '/parent/sdi'
      fullPath: '/parent/sdi'
      preLoaderRoute: typeof LayoutParentSdiRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/parent/monitor': {
      id: '/_layout/parent/monitor'
      path: '/parent/monitor'
      fullPath: '/parent/monitor'
      preLoaderRoute: typeof LayoutParentMonitorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/parent/exams': {
      id: '/_layout/parent/exams'
      path: '/parent/exams'
      fullPath: '/parent/exams'
      preLoaderRoute: typeof LayoutParentExamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coding/editor': {
      id: '/_layout/coding/editor'
      path: '/editor'
      fullPath: '/coding/editor'
      preLoaderRoute: typeof LayoutCodingEditorRouteImport
      parentRoute: typeof LayoutCodingRoute
    }
    '/_layout/exams/report/$sessionId': {
      id: '/_layout/exams/report/$sessionId'
      path: '/exams/report/$sessionId'
      fullPath: '/exams/report/$sessionId'
      preLoaderRoute: typeof LayoutExamsReportSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exams/play/$sessionId': {
      id: '/_layout/exams/play/$sessionId'
      path: '/exams/play/$sessionId'
      fullPath: '/exams/play/$sessionId'
      preLoaderRoute: typeof LayoutExamsPlaySessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutCodingRouteChildren {
  LayoutCodingEditorRoute: typeof LayoutCodingEditorRoute
  LayoutCodingIndexRoute: typeof LayoutCodingIndexRoute
}

const LayoutCodingRouteChildren: LayoutCodingRouteChildren = {
  LayoutCodingEditorRoute: LayoutCodingEditorRoute,
  LayoutCodingIndexRoute: LayoutCodingIndexRoute,
}

const LayoutCodingRouteWithChildren = LayoutCodingRoute._addFileChildren(
  LayoutCodingRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAchievementsRoute: typeof LayoutAchievementsRoute
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutChildrenRoute: typeof LayoutChildrenRoute
  LayoutCodingRoute: typeof LayoutCodingRouteWithChildren
  LayoutGrowthRoute: typeof LayoutGrowthRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPrizesRoute: typeof LayoutPrizesRoute
  LayoutReferralRoute: typeof LayoutReferralRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTasksRoute: typeof LayoutTasksRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutParentExamsRoute: typeof LayoutParentExamsRoute
  LayoutParentMonitorRoute: typeof LayoutParentMonitorRoute
  LayoutParentSdiRoute: typeof LayoutParentSdiRoute
  LayoutExamsIndexRoute: typeof LayoutExamsIndexRoute
  LayoutExamsPlaySessionIdRoute: typeof LayoutExamsPlaySessionIdRoute
  LayoutExamsReportSessionIdRoute: typeof LayoutExamsReportSessionIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAchievementsRoute: LayoutAchievementsRoute,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutChildrenRoute: LayoutChildrenRoute,
  LayoutCodingRoute: LayoutCodingRouteWithChildren,
  LayoutGrowthRoute: LayoutGrowthRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPrizesRoute: LayoutPrizesRoute,
  LayoutReferralRoute: LayoutReferralRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTasksRoute: LayoutTasksRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutParentExamsRoute: LayoutParentExamsRoute,
  LayoutParentMonitorRoute: LayoutParentMonitorRoute,
  LayoutParentSdiRoute: LayoutParentSdiRoute,
  LayoutExamsIndexRoute: LayoutExamsIndexRoute,
  LayoutExamsPlaySessionIdRoute: LayoutExamsPlaySessionIdRoute,
  LayoutExamsReportSessionIdRoute: LayoutExamsReportSessionIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CoinsLogsRoute: CoinsLogsRoute,
  LandingParentRoute: LandingParentRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  AddressesIndexRoute: AddressesIndexRoute,
  CoinLogsIndexRoute: CoinLogsIndexRoute,
  RedemptionsIndexRoute: RedemptionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
