/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VerifyEmailImport } from './routes/verify-email'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as RedemptionsIndexImport } from './routes/redemptions/index'
import { Route as CoinLogsIndexImport } from './routes/coin-logs/index'
import { Route as AddressesIndexImport } from './routes/addresses/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LandingParentImport } from './routes/landing/parent'
import { Route as CoinsLogsImport } from './routes/coins/logs'
import { Route as LayoutTasksImport } from './routes/_layout/tasks'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutReferralImport } from './routes/_layout/referral'
import { Route as LayoutPrizesImport } from './routes/_layout/prizes'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutGrowthImport } from './routes/_layout/growth'
import { Route as LayoutAdminImport } from './routes/_layout/admin'

// Create/Update Routes

const VerifyEmailRoute = VerifyEmailImport.update({
  path: '/verify-email',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const RedemptionsIndexRoute = RedemptionsIndexImport.update({
  path: '/redemptions/',
  getParentRoute: () => rootRoute,
} as any)

const CoinLogsIndexRoute = CoinLogsIndexImport.update({
  path: '/coin-logs/',
  getParentRoute: () => rootRoute,
} as any)

const AddressesIndexRoute = AddressesIndexImport.update({
  path: '/addresses/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LandingParentRoute = LandingParentImport.update({
  path: '/landing/parent',
  getParentRoute: () => rootRoute,
} as any)

const CoinsLogsRoute = CoinsLogsImport.update({
  path: '/coins/logs',
  getParentRoute: () => rootRoute,
} as any)

const LayoutTasksRoute = LayoutTasksImport.update({
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutReferralRoute = LayoutReferralImport.update({
  path: '/referral',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPrizesRoute = LayoutPrizesImport.update({
  path: '/prizes',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGrowthRoute = LayoutGrowthImport.update({
  path: '/growth',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/verify-email': {
      preLoaderRoute: typeof VerifyEmailImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/growth': {
      preLoaderRoute: typeof LayoutGrowthImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/prizes': {
      preLoaderRoute: typeof LayoutPrizesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/referral': {
      preLoaderRoute: typeof LayoutReferralImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tasks': {
      preLoaderRoute: typeof LayoutTasksImport
      parentRoute: typeof LayoutImport
    }
    '/coins/logs': {
      preLoaderRoute: typeof CoinsLogsImport
      parentRoute: typeof rootRoute
    }
    '/landing/parent': {
      preLoaderRoute: typeof LandingParentImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/addresses/': {
      preLoaderRoute: typeof AddressesIndexImport
      parentRoute: typeof rootRoute
    }
    '/coin-logs/': {
      preLoaderRoute: typeof CoinLogsIndexImport
      parentRoute: typeof rootRoute
    }
    '/redemptions/': {
      preLoaderRoute: typeof RedemptionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutGrowthRoute,
    LayoutItemsRoute,
    LayoutPrizesRoute,
    LayoutReferralRoute,
    LayoutSettingsRoute,
    LayoutTasksRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
  VerifyEmailRoute,
  CoinsLogsRoute,
  LandingParentRoute,
  AddressesIndexRoute,
  CoinLogsIndexRoute,
  RedemptionsIndexRoute,
])

/* prettier-ignore-end */
